# 服务端口
server:
  port: 8207
# 服务名
spring:
  application:
    name: service-orders
  # mysql数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yygh_order?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # 连接Mongodb
  data:
    mongodb:
      uri: mongodb://192.168.253.137:27017/test
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # redis
  redis:
    host: 192.168.253.137
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 5
        min-idle: 0
  # rabbitmq地址
#  rabbitmq:
#    host: 192.168.6.100
#    port: 5672
#    username: guest
#    password: guest
