#服务端口
server:
  port: 8160
#服务名
spring:
  application:
    name: service-user
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  # mysql数据库连接
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yygh_user?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  #返回json的全局时间格式
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.253.137
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        max-idle: 5
        #最小空闲
        min-idle: 0
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_key: a7482517235173ddb4083788de60b90e
    url: http://localhost:8160/yygh/user/wx/callback
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:space/jachen/yygh/cmn/mapper/*/*.xml
