############################################### 服务端口 ################################################################
server:
  port: 8160
############################################### spring #################################################################
spring:
  devtools:
    livereload:
      enabled: false  # remove Unable to start LiveReload server
  application:
    name: service-user
  profiles:
    active: dev  # 环境设置：dev、test、prod
  datasource:  # mysql数据库连接
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/yygh_user?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss  # 返回json的全局时间格式
    time-zone: GMT+8
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.253.137
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-wait: -1  # 最大阻塞等待时间(负数表示没限制)
        max-idle: 5
        min-idle: 0
############################################### 微信接口 ################################################################
wx:
  open:
    app_id: wxed9954c01bb89b47
    app_key: a7482517235173ddb4083788de60b90e
    url: http://localhost:8160/yygh/user/wx/callback
####################################### mybatis-plus配置 ################################################################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:space/jachen/yygh/cmn/mapper/*/*.xml
