############################################### 服务端口 ################################################################
server:
  port: 8206
############################################### spring #################################################################
spring:
  devtools:
    livereload:
      enabled: false # remove Unable to start LiveReload server
  application:
    name: service-oss
  profiles:
    active: dev  # 环境设置：dev、test、prod
  servlet:
    multipart:
      max-file-size: 1024MB  # 上传文件大小
      max-request-size: 1024MB
############################################### 阿里云服务 ###############################################################
aliyun:
  oss:  #阿里云OSS
    file:
      endpoint: 
      keyid: 
      keysecret: 
      bucketname: space-jachen  # bucket可以在控制台创建，也可以使用java代码创建
